try {
  throw new Error(".......");
} catch {
  console.log("An error");
}
